import {
  LayoutDashboard,
  Database,
  Users,
  UserCircle,
  Settings,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  Home,
  Bell,
  Search,
  Shield,
  Key,
  FileText,
  Calendar,
  BarChart3,
  Package,
  ShoppingCart,
  DollarSign,
  CreditCard,
  Building2,
  UsersRound,
  UserPlus,
  UserMinus,
  ClipboardList,
  Activity,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  HelpCircle,
  ChevronLeft,
  ChevronUp,
  PanelLeftClose,
  PanelLeft,
  LucideIcon,
} from "lucide-react";

// Map of icon names from database to Lucide components
export const iconMap: Record<string, LucideIcon> = {
  // Dashboard & Layout
  LayoutDashboard,
  Database,
  Users,
  UserCircle,
  Settings,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  Home,
  Bell,
  Search,
  Shield,
  Key,
  FileText,
  Calendar,
  BarChart3,
  Package,
  ShoppingCart,
  DollarSign,
  CreditCard,
  Building2,
  UsersRound,
  UserPlus,
  UserMinus,
  ClipboardList,
  Activity,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  HelpCircle,
  ChevronLeft,
  ChevronUp,
  PanelLeftClose,
  PanelLeft,
};

// Get icon component from name
export function getIcon(iconName: string): LucideIcon {
  return iconMap[iconName] || LayoutDashboard; // Default to LayoutDashboard
}

// Icon selector component props
export interface IconSelectorProps {
  value: string;
  onChange: (value: string) => void;
}

// Common icons for selection
export const iconOptions = [
  { value: "LayoutDashboard", label: "Dashboard", icon: LayoutDashboard },
  { value: "Database", label: "Database", icon: Database },
  { value: "Users", label: "Users", icon: Users },
  { value: "UserCircle", label: "User Circle", icon: UserCircle },
  { value: "Settings", label: "Settings", icon: Settings },
  { value: "FileText", label: "File Text", icon: FileText },
  { value: "Calendar", label: "Calendar", icon: Calendar },
  { value: "BarChart3", label: "Bar Chart", icon: BarChart3 },
  { value: "Package", label: "Package", icon: Package },
  { value: "ShoppingCart", label: "Shopping Cart", icon: ShoppingCart },
  { value: "DollarSign", label: "Dollar", icon: DollarSign },
  { value: "CreditCard", label: "Credit Card", icon: CreditCard },
  { value: "Building2", label: "Building", icon: Building2 },
  { value: "UsersRound", label: "Users Round", icon: UsersRound },
  { value: "UserPlus", label: "User Plus", icon: UserPlus },
  { value: "UserMinus", label: "User Minus", icon: UserMinus },
  { value: "ClipboardList", label: "Clipboard", icon: ClipboardList },
  { value: "Activity", label: "Activity", icon: Activity },
  { value: "Clock", label: "Clock", icon: Clock },
  { value: "Shield", label: "Shield", icon: Shield },
  { value: "Key", label: "Key", icon: Key },
  { value: "Home", label: "Home", icon: Home },
  { value: "Bell", label: "Bell", icon: Bell },
  { value: "Search", label: "Search", icon: Search },
];
